travis:
  secure:
    BINSTAR_TOKEN: F7jAw3Be7cr6Q1XMs+lVyTMuxctNtmtWaoDGqyUeqe6xzsQDALEgLsObHHxHDpg5Z6NrlsHEsGo02yYsoFGohr+mWfF48EUZ3CEqT+e/1NkJArRCiQHat1u6RJQx5Q9YvIgJXcg231uN/HRSJhrmHlbgJ1kywQcAxtVMeo+64VMzNmN8JUYcDgWieFuaz43LYetUliMDaZplGWITOcLbW/xi2aDioPhpmWO24JN4cyR78dnBmTxSni4iAIqHnKAt9FI1IrD/EyQrmAuuaCG+7Db0fHzffukJhg+A7bZYRCrOTovc3NAdEA5y4MZYmmRXBpUsGLJLcNkgwAvB9unVikVxFpZik4R2mosaJlKiz7Ua/f9p38C28GSm5l5Uo2ro62bUt03CkcwqzcGxU2PCspZx8j2wzCT7QAcKtpaiDNi83fwmgKFsSizE6pmhnSuqDTOtI0GI2Ai6UNrVPXsRIrVSvUzgzf3daDacu6LvW2gNHh99GKt/1uxHuSoNpG+STnOr0vzsFae4zfDzmxSi1gX97cV8qoWdMjJ51kMlof4bxrXdT18mnsIacjIwhu+RRddYM2RwhG1fsANLNxyMJF0sD/MAYTu+ODmVqd9ixkOLpUpAYl8WU6P3ajHKWlIM82TwcawbMwiWr6pCH74mKGieNIZH7JyF26xtRLu+WVM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
